$:
  # vscode 事件：专供页面中启动远程开发用
  vscode:
    - docker:
        # 自定义镜像作为开发环境
        image: cnbcool/default-dev-env:latest
      services:
        - vscode
        - docker
      runner :
        cpus: 1
      imports: https://cnb.cool/ChuangYiLLC/Tech/secrets/-/blob/sdcom/docker.yml
      stages:
        - name: ls
          script: ls -al
        - name: docker-codeserver
          script: code-server --install-extension ritwickdey.LiveServer
        - name: sudo
          script: apt-get update && apt-get install -y sudo curl wget
  # Push 事件: 推送时使用
  push: 
    - runner: 
        cpus: 1
      imports: https://cnb.cool/BlueScreen-Studio/Tech/secrets/-/blob/sdcom/github.yml
      stages:
        - name: sync to github
          image: tencentcom/git-sync         
          settings:
            target_url: https://github.com/SDCOM-0415/sdcom-0415.github.io.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
            git_user: ${GIT_USERNAME}
            git_email: ${GIT_EMAIL}
            branch: main      